name: Frontline
on:
  schedule:
    - cron: '30 13 * * 1-5'  # every weekday at 6:30am (14:00 UTC)

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env:
      USER_LOGIN: ${{ secrets.user_login }}
      USER_PASS: ${{ secrets.user_pass }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: deps install
        run: yarn install

      - name: Run
        run: node frontline.js
