name: Frontline
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 14 * * *'  # every day at 7am (14:00 PST)

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env:
      USER_LOGIN: ${{ secrets.user_login }}
      USER_PASS: ${{ secrets.user_pass }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: yarn install

      - name: Run
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: node frontline.js
